repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/klieret/jekyll-relative-url-check
    rev: v2.0.2
    hooks:
      - id: jekyll-relative-url-check-html
      - id: jekyll-relative-url-check-markdown

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.42.0
    hooks:
      - id: markdownlint
      - id: markdownlint-fix
